Create data providers
emanrdesu/November pull request #2
Opened 2022-11-06 23:34 UTC by emanrdesu

2022-11-06 23:57 UTC, dentaylor requested changes

2022-11-06 23:57 UTC, dentaylor commented on java.exercises/src/test/java/DataProviderTests.java
> +		var expectedState = "Texas";
Insert a line between the three sections (Arrange, Act, Assert)

2022-11-06 23:57 UTC, dentaylor commented on java.exercises/src/test/java/LocationBuilder.java
> +	public LocationBuilder withState(State s) {
Don't use abbreviations as parameter names. Spell it out 
public LocationBuilder withState(State state);

2022-11-07 00:18 UTC, dentaylor approved these changes

2022-11-07 00:18 UTC, dentaylor commented on java.exercises/src/test/java/DataProviderTests.java
> +		Assert.assertEquals(actualState, expectedState, errorMessage);
Suggest inlining the error message since you're only using it once.

2022-11-07 00:20 UTC, emanrdesu commented on java.exercises/src/test/java/DataProviderTests.java
> +		Assert.assertEquals(actualState, expectedState, errorMessage);
I know, but I don't like lines being very long, is it ok if I leave as is?

2022-11-07 00:26 UTC, merged